version: "3.5"
services:
  app:
    image: hpccbk/hadoop-docker-base:2.7.2
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net
    volumes:
      - ./data:/data
networks:
  hadoop-net:
    external:
      name: hadoop_hadoop
